const images = {
    deleteIcon: require('@images/cart/minus.png'),
    dropdownIcon: require('@images/cart/up_down_arrow.png'),
    radioCheck: require('@images/productDetails/radio-check.png'),
    radioUncheck: require('@images/productDetails/radio-uncheck.png'),
    checked:require('@images/checked.png'),
    user:require('@images/user.png'),
    playIcon:require('@images/playIcon.png'),
    unChecked:require('@images/unChecked.png'),
    checkedIcon:require('@images/checkedIcon.png'),
    cardFront:require('@images/card-front.png'),
    cardBack:require('@images/card-back.png'),
    masterCard:require('@images/mastercard.png'),
    visaCard:require('@images/visa.png'),
    amexpCard:require('@images/american-express.png'),
    emptyCircle:require('@images/emptyCircle.png'),
    success:require('@images/success.png'),
    noimage:require('@images/noimage.png'),
    productsinGrid:require('@images/grid.png'),
    productsinList:require('@images/list-with-dots.png'),
    addFriend:require('@images/addFriend.png'),
    cameraIcon:require('@images/camera.png'),
}
export default images
